### ISSUE TITLE
Input groups button margin difference with no-icons

### ISSUE THREAD

**Issue by randymorris** [jsdelivr/bootstrapcdn#197]
The no-icons version of Bootstrap seems to be tweaking the margin on input group buttons differently than the standard Bootstrap.

``` css
.input-group-btn:last-child>.btn {
margin-left: -1px;
}
```

With the standard Bootstrap: http://jsfiddle.net/qVHWW/
With the no-icons Bootstrap: http://jsfiddle.net/h4D9w/

This difference is most noticeable when the input has focus.
