### ISSUE TITLE
Font Awesome always downloads fonts over https

### ISSUE THREAD

**Issue by DaleLJefferson** [jsdelivr/bootstrapcdn#33]
Taken from http://netdna.bootstrapcdn.com/font-awesome/2.0/css/font-awesome.css

``` css
@font-face{
    font-family:FontAwesome;
    src:url(https://netdna.bootstrapcdn.com/font-awesome/2.0/font//fontawesome-webfont.eot?#iefix) format('eot'),
    url(https://netdna.bootstrapcdn.com/font-awesome/2.0/font//fontawesome-webfont.woff) format('woff'),
    url(https://netdna.bootstrapcdn.com/font-awesome/2.0/font//fontawesome-webfont.ttf) format('truetype'),
    url(https://netdna.bootstrapcdn.com/font-awesome/2.0/font//fontawesome-webfont.svg#FontAwesome) format('svg');
    font-weight:400;font-style:normal;}
```

Is there a reason we are not using relate urls?
